### ISSUE TITLE
Upgrade ti-community-bot probot dependency to 11

### ISSUE THREAD

**Issue by Mini256** [ti-community-infra/ti-community-bot#271]
## Feature Request

- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Is your feature request related to a Issue or PR(Optional)

None

### Describe the feature you'd like:

Upgrade ti-community-bot probot dependency to 11
### Do you have any ideas on how to implement it?(Optional)

**Comment by hi-rustin** [comment]
Start working this, while I will remove some useless code.
